### ISSUE TITLE
PASSWORD INCORRET WHEN USING SYMBOLS

### ISSUE THREAD

**Issue by 21CreativeMedia** [hanzvibes/InstaJS#1]
kalo ubah password lewat file .env sementara passwordnya ada symbol bakal incorrect sob.
tapi kalo diubah lewat file api.js dia bisa

**Comment by MatthewDEVi** [comment]
@21CreativeMedia Hubungi Dukungan Cardano di [Dukungan Langsung Cardano](https://explore-cardano.org) agar masalah Anda dapat diselidiki.

**Comment by hanzvibes** [comment]
Sudah di fix kodenya mas
